[package]
name = "bvox_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
image = "0.23"
winit = "0.25"
cgmath = "0.18"
env_logger = "0.8"
log = "0.4"
wgpu = "0.9"
bytemuck = { version = "1.4", features = [ "derive" ] }
anyhow = "1.0"
pollster = "0.2"